name: akeyless-test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: https://hvp.akeyless.io
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/DevOps/Automation/Teamcity/Ansible/remote_linux_user DevOps/Automation/Teamcity/Ansible/remote_linux_user | remote_linux_user_secret ;
            secret/data/DevOps/Automation/Teamcity/Ansible/remote_windows_user DevOps/Automation/Teamcity/Ansible/remote_windows_user | remote_windows_user_secret ;
      - name: Secret from Akeyless
        run: |
          echo "remote_linux_user='${{ env.remote_linux_user_secret }}'" >> "log.out"
          echo "remote_windows_user='${{ env.remote_windows_user_secret }}'" >> "log.out"
        

      - uses: actions/upload-artifact@v4
        with:
          path: "log.out"
